PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT 
(REPLACE(STR(?parent), "http://virtual-assembly.org/ontologies/pair#", "pair:") AS ?id_parent)
(REPLACE(STR(?classe), "http://virtual-assembly.org/ontologies/pair#", "pair:") AS ?id_classe)
?classe
(STR(?libelle_fr) AS ?label_francais)
(STR(?definition_fr) AS ?definition_francais)
(STR(?libelle_en) AS ?libelle_anglais)
(STR(?definition_en) AS ?definition_anglais)
WHERE {
	?classe a owl:Class . FILTER(isIRI(?classe))
    OPTIONAL { ?classe rdfs:subClassOf ?parent . FILTER(isIRI(?parent)) }
	OPTIONAL { ?classe rdfs:label ?libelle_fr FILTER(lang(?libelle_fr) = "fr") . }
	OPTIONAL { ?classe rdfs:comment ?definition_fr FILTER(lang(?definition_fr) = "fr") . }
	OPTIONAL { ?classe rdfs:label ?libelle_en FILTER(lang(?libelle_en) = "en") . }
	OPTIONAL { ?classe rdfs:comment ?definition_en FILTER(lang(?definitiodefinition_enn_anglais) = "en") . }
}
ORDER BY ?parent1 ?classe